name: Process JSON Input

on:
  push:
  workflow_dispatch:
    inputs:
      jsonInput:
        description: "JSON object input"
        required: true
        default: '{"key1":"value1","key2":"value2"}'

jobs:
  process-json:
    runs-on: ubuntu-latest
    steps:
      - name: Print JSON Input
        run: |
          echo "Received JSON: ${{ inputs.jsonInput }}"
