name: Postman Newman API Tests

on:
  workflow_call:
    inputs:
      postman_collection_location:
        type: string
        default: ./api.postman_collection.json
      postman_env_file_name:
        type: string

jobs:
  check-collection-availability:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if collection file exists
        id: check_file
        run: |
          if [ ! -f ${{ inputs.postman_collection_location }} ]; then
            echo "Collection file not found!"
            exit 1  # Fail the job if the file doesn't exist
          fi

  run-api-testing:
    needs: check-collection-availability
    if: needs.check-collection-availability.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: download env file
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.postman_env_file_name }}
          path: ./postman

      - name: check env file content
        run: |
          cat ./postman/${{ inputs.postman_env_file_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install -g newman newman-reporter-ctrf-json

      - name: Run Newman tests
        run: |
          newman run ${{ inputs.postman_collection_location }} \
            --environment ./postman/${{ inputs.postman_env_file_name }} \
            -r cli,ctrf-json \
            --reporter-ctrf-json-test-type api \
            --reporter-ctrf-json-app-name 'Api Testing result'

      - name: Export test summary
        run: npx github-actions-ctrf ./ctrf/ctrf-report.json
