name: Postman Newman API Tests

on:
  push:
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Newman tests in Docker
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/etc/newman \
          --entrypoint sh \
          postman/newman:latest -c "
          npm install newman-reporter-ctrf-json &&
          newman run /etc/newman/api.postman_collection.json \
          -r cli,ctrf-json \
          --reporter-ctrf-json-test-type api 
          --reporter-ctrf-json-app-name Api Testing result
          "
          
      - name: Check if report exists
        run: ls -l ./report.html

      - name: Export test summary
        if: always()
        run: npx github-actions-ctrf ./ctrf/ctrf-report.json
