name: Postman Newman API Tests

on:
  push:
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Newman tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/etc/newman \
          postman/newman:latest sh -c "
            npm install -g newman-reporter-html && 
            newman run /etc/newman/api.postman_collection.json \
            --reporters cli,html \
            --reporter-html-export /etc/newman/report.html
          "
      
      - name: Check if report exists
        run: ls -l ./report.html
        
      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: ./report.html
