name: Postman Newman API Tests

on:
  push:
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g newman newman-reporter-ctrf-json  # Install Newman and the custom reporter

      - name: Run Newman tests
        run: |
          newman run ./api.postman_collection.json \
            -r cli,ctrf-json \
            --reporter-ctrf-json-test-type api \
            --reporter-ctrf-json-app-name 'Api Testing result'

      - name: Check if report exists
        run: ls -l ./ctrf/ctrf-report.json

      - name: Export test summary
        if: always()
        run: npx github-actions-ctrf ./ctrf/ctrf-report.json
