name: Postman Newman API Tests

on:
  workflow_dispatch:
    inputs:
      env_content:
        description: 'Content of postman environment file'
        default: '{"id":"env","values":[]}'

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check if collection file exists
        id: check_file
        run: |
          if [ ! -f ./api.postman_collection.json ]; then
            echo "Collection file not found!"
            exit 1  # Fail the job if the file doesn't exist
          fi

      - name: prepare env file
        if: steps.check_file.outcome == 'success'
        run: |
          echo "${{ github.event.inputs.env_file_content }}" > postman_env.json

      - name: Set up Node.js
        if: steps.check_file.outcome == 'success'
        uses: actions/setup-node@v3

      - name: Install dependencies
        if: steps.check_file.outcome == 'success'
        run: |
          npm install -g newman newman-reporter-ctrf-json

      - name: Run Newman tests
        if: steps.check_file.outcome == 'success'        
        run: |
          newman run ./api.postman_collection.json \
            --environment postman_env.json \
            -r cli,ctrf-json \
            --reporter-ctrf-json-test-type api \
            --reporter-ctrf-json-app-name 'Api Testing result'

      - name: Export test summary
        if: steps.check_file.outcome == 'success'
        run: npx github-actions-ctrf ./ctrf/ctrf-report.json
