name: Postman Newman API Tests

on:
  push:
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Newman tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/etc/newman \
            postman/newman:latest run /etc/newman/path/to/your/postman_collection.json \
            --reporters cli,html \
            --reporter-html-export /etc/newman/report.html  # Specify output path for HTML report
          
      - name: Upload Newman Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: ./report.html
