name: Test api

on:
  push:

jobs:
  build-env-and-call:
    uses: ntqdinh-axonivy/OpenWeatherApiTestSample/.github/workflows/api.yml@master
    with:
      postman_collection_location: ./api.postman_collection.json
    secrets:
      postman_env_content: ${{ secrets.postman_env_content }}